#
# -*- coding: utf-8 -*-
# Copyright 2020 Datacom (Teracom Telematica S/A) <datacom.com.br>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dmos_linkagg module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class LinkaggArgs(object):  # pylint: disable=R0903
    """The arg spec for the dmos_linkagg module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'lag': {'elements': 'dict',
                                                    'options': {'admin_status': {'choices': ['up',
                                                                                             'down'],
                                                                                 'type': 'str'},
                                                                'description': {'type': 'str'},
                                                                'interface': {'elements': 'dict',
                                                                              'options': {'name': {'required': True,
                                                                                                   'type': 'str'},
                                                                                          'port_prio': {'type': 'int'}},
                                                                              'type': 'list'},
                                                                'lag_id': {'required': True,
                                                                           'type': 'int'},
                                                                'load_balance': {'choices': ['dst-ip',
                                                                                             'dst-mac',
                                                                                             'dynamic',
                                                                                             'enhanced',
                                                                                             'src-dst-ip',
                                                                                             'src-dst-mac',
                                                                                             'src-ip',
                                                                                             'src-mac'],
                                                                                 'type': 'str'},
                                                                'max_active': {'type': 'int'},
                                                                'min_active': {'type': 'int'},
                                                                'mode': {'choices': ['active',
                                                                                     'passive',
                                                                                     'static'],
                                                                         'type': 'str'},
                                                                'period': {'choices': ['long',
                                                                                       'short'],
                                                                           'type': 'str'}},
                                                    'type': 'list'},
                                            'sys_prio': {'type': 'int'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
