#
# -*- coding: utf-8 -*-
# Copyright 2020 Datacom (Teracom Telematica S/A) <datacom.com.br>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dmos_sntp module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class SntpArgs(object):  # pylint: disable=R0903
    """The arg spec for the dmos_sntp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'auth': {'type': 'bool'},
                                            'auth_key': {'elements': 'dict',
                                                         'options': {'id': {'required': True,
                                                                            'type': 'int'},
                                                                     'pass': {'type': 'str'}},
                                                         'type': 'list'},
                                            'client': {'type': 'bool'},
                                            'max_poll': {'type': 'int'},
                                            'min_poll': {'type': 'int'},
                                            'server': {'elements': 'dict',
                                                       'options': {'address': {'required': True,
                                                                               'type': 'str'},
                                                                   'key_id': {'type': 'int'}},
                                                       'type': 'list'},
                                            'source': {'options': {'ipv4': {'type': 'str'},
                                                                   'ipv6': {'type': 'str'}},
                                                       'type': 'dict'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
