#
# -*- coding: utf-8 -*-
# Copyright 2020 Datacom (Teracom Telematica S/A) <datacom.com.br>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dmos_l2_interface module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class L2_interfaceArgs(object):  # pylint: disable=R0903
    """The arg spec for the dmos_l2_interface module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'interface_name': {'required': True, 'type': 'str'},
                                            'native_vlan_id': {'type': 'int'},
                                            'qinq': {'type': 'bool'},
                                            'storm_control': {'elements': 'dict',
                                                              'options': {'percent': {'default': 1,
                                                                                      'type': 'float'},
                                                                          'traffic': {'choices': ['broadcast',
                                                                                                  'multicast',
                                                                                                  'unicast'],
                                                                                      'required': True,
                                                                                      'type': 'str'}},
                                                              'type': 'list'},
                                            'tpid': {'choices': ['0x88a8', '0x8100', '0x9100'],
                                                     'type': 'str'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
