#
# -*- coding: utf-8 -*-
# Copyright 2020 Datacom (Teracom Telematica S/A) <datacom.com.br>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dmos_twamp module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class TwampArgs(object):  # pylint: disable=R0903
    """The arg spec for the dmos_twamp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'reflector': {'options': {'admin_status': {'choices': ['up',
                                                                                                   'down'],
                                                                                       'type': 'str'},
                                                                      'ipv4': {'options': {'client_address': {'elements': 'dict',
                                                                                                              'options': {'address': {'required': True,
                                                                                                                                      'type': 'str'},
                                                                                                                          'state': {'choices': ['enable',
                                                                                                                                                'disable'],
                                                                                                                                    'type': 'str'}},
                                                                                                              'type': 'list'},
                                                                                           'client_network': {'elements': 'dict',
                                                                                                              'options': {'network': {'required': True,
                                                                                                                                      'type': 'str'},
                                                                                                                          'state': {'choices': ['enable',
                                                                                                                                                'disable'],
                                                                                                                                    'type': 'str'}},
                                                                                                              'type': 'list'}},
                                                                               'type': 'dict'},
                                                                      'ipv6': {'options': {'client_address': {'elements': 'dict',
                                                                                                              'options': {'address': {'required': True,
                                                                                                                                      'type': 'str'},
                                                                                                                          'state': {'choices': ['enable',
                                                                                                                                                'disable'],
                                                                                                                                    'type': 'str'}},
                                                                                                              'type': 'list'},
                                                                                           'client_network': {'elements': 'dict',
                                                                                                              'options': {'network': {'required': True,
                                                                                                                                      'type': 'str'},
                                                                                                                          'state': {'choices': ['enable',
                                                                                                                                                'disable'],
                                                                                                                                    'type': 'str'}},
                                                                                                              'type': 'list'}},
                                                                               'type': 'dict'},
                                                                      'port': {'type': 'int'}},
                                                          'type': 'dict'},
                                            'sender': {'options': {'admin_status': {'choices': ['up',
                                                                                                'down'],
                                                                                    'type': 'str'},
                                                                   'connection': {'elements': 'dict',
                                                                                  'options': {'admin_status': {'choices': ['up',
                                                                                                                           'down'],
                                                                                                               'type': 'str'},
                                                                                              'id': {'required': True,
                                                                                                     'type': 'int'},
                                                                                              'ipv4': {'options': {'source_address': {'type': 'str'},
                                                                                                                   'target_address': {'type': 'str'}},
                                                                                                       'type': 'dict'},
                                                                                              'ipv6': {'options': {'source_address': {'type': 'str'},
                                                                                                                   'target_address': {'type': 'str'}},
                                                                                                       'type': 'dict'},
                                                                                              'number_of_packets': {'type': 'int'},
                                                                                              'server_port': {'type': 'int'},
                                                                                              'test_interval': {'type': 'int'},
                                                                                              'test_session': {'elements': 'dict',
                                                                                                               'options': {'dscp': {'type': 'int'},
                                                                                                                           'id': {'required': True,
                                                                                                                                  'type': 'int'},
                                                                                                                           'ipv4': {'options': {
                                                                                                                               'source_address':
                                                                                                                                   {'type': 'str'},
                                                                                                                               'target_address':
                                                                                                                                   {'type': 'str'}},
                                                                                                                           'type': 'dict'},
                                                                                                                           'ipv6': {
                                                                                                                               'options': {
                                                                                                                                   'source_address': {
                                                                                                                                       'type': 'str'
                                                                                                                                   },
                                                                                                                                   'target_address': {
                                                                                                                                       'type': 'str'
                                                                                                                                   }
                                                                                                                               },
                                                                                                                               'type': 'dict'},
                                                                                                                           'max_port': {'type': 'int'},
                                                                                                                           'min_port': {'type': 'int'},
                                                                                                                           'packet_size': {'type': 'int'}},
                                                                                                               'type': 'list'}},
                                                                                  'type': 'list'}},
                                                       'type': 'dict'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
