#
# -*- coding: utf-8 -*-
# Copyright 2020 Datacom (Teracom Telematica S/A) <datacom.com.br>
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the dmos_user module
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


class UserArgs(object):  # pylint: disable=R0903
    """The arg spec for the dmos_user module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
                                'options': {'alias': {'elements': 'dict',
                                                      'options': {'expansion': {'type': 'str'},
                                                                  'name': {'type': 'str'}},
                                                      'type': 'list'},
                                            'description': {'type': 'str'},
                                            'name': {'type': 'str'},
                                            'session': {'options': {'complete_on_space': {'type': 'bool'},
                                                                    'devtools': {'type': 'bool'},
                                                                    'display_level': {'type': 'int'},
                                                                    'history': {'type': 'int'},
                                                                    'idle_timeout': {'type': 'int'},
                                                                    'ignore_leading_space': {'type': 'bool'},
                                                                    'paginate': {'type': 'bool'},
                                                                    'show_defaults': {'type': 'bool'}},
                                                        'type': 'dict'}},
                                'type': 'list'},
                     'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
                               'default': 'merged',
                               'type': 'str'}}  # pylint: disable=C0301
